### get all movies
GET http://localhost:777/movies

### get by ID
GET http://localhost:777/movies/0ed9cc1a-d195-11ee-8666-18c04d1c9c8f

### create movie
POST http://localhost:777/movies
Content-Type: application/json

{
    "title": "The Fellowship Of The Ring",
    "poster": "https://m.media-amazon.com/images/I/81EBp0vOZZL.jpg"
}

### update a movie
PATCH http://localhost:777/movies/0ed9cda0-d195-11ee-8666-18c04d1c9c8f
Content-Type: application/json

{
    "poster": "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg"
}

### delete a movie
DELETE  http://localhost:777/movies/241bf55d-b649-4109-af7c-0e6890ded3fc



### get all series
GET http://localhost:777/series

### get by ID
GET http://localhost:777/series/0edafe53-d195-11ee-8666-18c04d1c9c8f

### create serie
POST http://localhost:777/series
Content-Type: application/json

{
    "title": "Mashle Magic And Muscles",
    "poster": "https://static.wikia.nocookie.net/doblaje/images/d/da/MASHLE.jpg/revision/latest?cb=20230323125818&path-prefix=es"
}

### uopdate serie
PATCH http://localhost:777/series/ca725a59-d19a-11ee-8666-18c04d1c9c8f
Content-Type: application/json

{
    "poster": "https://upload.wikimedia.org/wikipedia/en/1/17/Mashle%2C_volume_1_cover.jpg"
}

### delete a serie
DELETE  http://localhost:777/series/af168cd1-0d48-47b7-a1de-68517f4bf91d



### get all books
GET http://localhost:777/books

### get by ID
GET http://localhost:777/books/068e4c61-d199-11ee-8666-18c04d1c9c8f

### create book
POST http://localhost:777/books
Content-Type: application/json

{
    "title": "How To Make The Best Coffee At Home",
    "poster": "https://m.media-amazon.com/images/I/81U69Tmw41L._AC_UF1000,1000_QL80_.jpg"
}

### update a movie
PATCH http://localhost:777/books/3b79e9ae-d199-11ee-8666-18c04d1c9c8f
Content-Type: application/json

{
    "title": "The World Atlas Of Coffee"
}

### delete a book
DELETE  http://localhost:777/books/cd6f7ca8-8e7b-44cb-ba41-c289632faa24